# Server Configuration
server:
  port: 8000

# Spring Configuration
spring:
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:storedb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 Console (for viewing database)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Jackson Configuration
  jackson:
    property-naming-strategy: SNAKE_CASE

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Creates tables on startup, drops on shutdown
    show-sql: true           # Show SQL queries in logs
    properties:
      hibernate:
        format_sql: true     # Format SQL nicely
        use_sql_comments: true # Add comments to SQL

# Logging Configuration
logging:
  level:
    com.avivse.storeservice: INFO     # Changed from DEBUG to reduce noise
    org.springframework.web: INFO     # Changed from DEBUG to reduce noise
    org.hibernate.SQL: DEBUG          # SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parameters
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true
  security:
    enabled: false  # For development - enable for production
  info:
    env:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s
    export:
      prometheus:
        enabled: true
        histogram-flavor: prometheus

# SpringDoc Configuration
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs

# Application Information
info:
  app:
    name: Store Service
    description: Microservice for managing store information
    version: 1.0.0
    environment: development
  java:
    version: 17
  build:
    time: 2024-01-01